//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BendMX.rc
//
#define IDD_WELCOMEMSGS                 5
#define IDB_USERMODES                   6
#define IDD_GENERAL                     101
#define IDC_ADDCHANNEL2                 1014
#define IDC_REMOVECHANNEL2              1170
#define IDC_WELCOMES                    1312
#define IDD_BENDMX                      4000
#define IDD_COLORS                      4001
#define IDD_FILTER                      4002
#define IDB_PREF                        4003
#define IDD_MESSAGES                    4004
#define IDD_CHATDLG                     4005
#define IDD_ABOUT                       4006
#define IDD_SIMPLEBOT                   4007
#define IDD_KICKIT_SERVER               4008
#define IDB_BMX_LOGO                    4009
#define IDS_SUBCLASS_FAILED             4010
#define IDS_REPAIRHOOK                  4011
#define IDD_UTIL                        4012
#define IDB_KICKIT                      4013
#define IDC_APPLY                       4100
#define IDC_PREFBAR                     4101
#define IDC_STATIC_LANG                 4102
#define IDC_LANG                        4103
#define IDC_REMOVE                      4104
#define IDC_RELOAD_ALL                  4105
#define IDC_STATIC_INCOMING             4106
#define IDC_TIMEA                       4107
#define IDC_BLOCK_HTTP                  4108
#define IDC_TIMEB                       4109
#define IDC_BLOCK_ASCII_ART             4110
#define IDC_STATIC_TIMEA                4111
#define IDC_BLOCK_PRIVATE_RCMS          4112
#define IDC_STATIC_TIMEB                4113
#define IDC_STATIC_PLUGINS              5004
#define IDC_PLUGINLIST                  5005
#define IDC_STATIC_CONFIG_RECT          5006
#define IDC_UNLOAD_ALL                  5009
#define IDC_STATIC_NICKNAME             5010
#define IDC_NICKNAME                    5011
#define IDC_STATIC_OPTIONS              5012
#define IDC_CHANNELNAME                 5013
#define IDC_ADDCHANNEL                  5014
#define IDC_CHANNELLIST                 5015
#define IDC_REMOVECHANNEL               5016
#define IDC_ALLCHANNELS                 5017
#define IDC_NICKALERT                   5018
#define IDC_ENABLE_HISTORY              5019
#define IDC_LINES                       5021
#define IDC_LINESNUM                    5023
#define IDC_HISTORDEPTH                 5024
#define IDC_STATIC_LINES                5025
#define IDC_STATIC_DEPTH                5026
#define IDC_STATIC_MISC                 5027
#define IDC_REPAIR                      5028
#define IDC_FONTHELP                    5029
#define IDC_ENABLE_NICKS                5030
#define IDC_STATIC_GUEST                5031
#define IDC_STATIC_OPS                  5032
#define IDC_COLOR_GUEST                 5033
#define IDC_COLOR_OPS                   5034
#define IDC_COLOR_HOST                  5035
#define IDC_COLOR_YOU                   5036
#define IDC_CHANGE_GUEST                5037
#define IDC_CHANGE_OPS                  5038
#define IDC_CHANGE_HOST                 5039
#define IDC_CHANGE_YOU                  5040
#define IDC_STATIC_OPS_PRE              5041
#define IDC_PRE_REG_ADD                 5042
#define IDC_OP_ADD                      5043
#define IDC_REG_PREFIX                  5044
#define IDC_OP_REM                      5045
#define IDC_STATIC_MESSAGE              5047
#define IDC_STATIC_NICKENC_MSG          5048
#define IDC_MSG_FRONT                   5049
#define IDC_STATIC_FRONT_MSG            5050
#define IDC_STATIC_HOST_PREF            5051
#define IDC_PRE_HOST_ADD                5052
#define IDC_OP_ADD2                     5053
#define IDC_HOST_PREFIX                 5054
#define IDC_OP_REM2                     5055
#define IDC_MSG_END                     5056
#define IDC_STATIC_END_MSG              5057
#define IDC_STATIC_NICKENC_MSG2         5058
#define IDC_STATIC_COLOR_ENC_MSG_PREV   5059
#define IDC_ENC_MSG_COLOR               5060
#define IDC_COLOR_MESSAGE               5061
#define IDC_STATIC_NICKNAME_MSG         5062
#define IDC_STATIC_COLOR_MSG_PREV       5063
#define IDC_STATIC_ACTION               5064
#define IDC_ACTION_FRONT                5065
#define IDC_STATIC_FRONT_ACTION         5066
#define IDC_ACTION_END                  5067
#define IDC_STATIC_END_ACTION           5068
#define IDC_ENC_ACTION_COLOR            5069
#define IDC_COLOR_ACTION                5070
#define IDC_STATIC_NICKNAME_ACTION      5071
#define IDC_STATIC_COLOR_ACTION_PREV    5072
#define IDC_STATIC_COLOR_ENG_ACTION_PREV 5073
#define IDC_STATIC_MISCCOLOR            5074
#define IDC_BACKG                       5075
#define IDC_STATIC_BG                   5076
#define IDC_SOUNDEFFECT                 5077
#define IDC_TOPIC                       5078
#define IDC_MOTD                        5079
#define IDC_JOIN                        5080
#define IDC_PART                        5081
#define IDC_STATIC_TOPIC                5082
#define IDC_STATIC_MOTD                 5083
#define IDC_STATIC_JOIN                 5084
#define IDC_STATIC_PART                 5085
#define IDC_STATIC_FONT                 5086
#define IDC_FONT                        5087
#define IDC_STATIC_SIZE                 5088
#define IDC_FONTSIZE                    5089
#define IDC_ENCODING                    5090
#define IDC_STATIC_ENCODING             5091
#define IDC_BLOCK_TOPIC                 5096
#define IDC_BLOCK_MOTD                  5097
#define IDC_BLOCK_MSG                   5098
#define IDC_BLOCK_ADMIN                 5099
#define IDC_STATIC_TRUSTED              5100
#define IDC_TRUSTED_ADD                 5101
#define IDC_TRUSTED_ADD_BTN             5102
#define IDC_TRUSTED_LIST                5103
#define IDC_TRUSTED_REM_BTN             5104
#define IDC_FILTER_ADD                  5105
#define IDC_FILTER_ADD_BTN              5106
#define IDC_FILTER_LIST                 5107
#define IDC_FILTER_REM_BTN              5108
#define IDC_QUICKREM                    5109
#define IDC_QUICKUP                     5110
#define IDC_QUICKDOWN                   5111
#define IDC_STATIC_QUICK                5112
#define IDC_STATIC_JOINPART             5113
#define IDC_MSG_ADD                     5114
#define IDC_MSG_ADD_BTN                 5115
#define IDC_STATIC_PART_VAR             5116
#define IDC_STATIC_JOIN_VAR             5117
#define IDC_STATIC_WINAMP               5118
#define IDC_STATIC_MUSIC                5119
#define IDC_NOWLISTENING                5120
#define IDC_STATIC_VIDEO                5121
#define IDC_NOW_WATCHING                5122
#define IDC_STATIC_VARS                 5123
#define IDC_STATIC_VARS2                5124
#define IDC_TIMESTAMP                   5125
#define IDC_GREETING                    5126
#define IDC_STATIC_GREETING             5127
#define IDC_BOLD                        5128
#define IDC_ITALIC                      5129
#define IDC_UNDERLINE                   5130
#define IDC_STATIC_WORDFILTER           5131
#define IDC_STARS                       5132
#define IDC_FILTERXTREM                 5133
#define IDC_IGNORE                      5134
#define IDC_LPGPL                       5135
#define IDC_STATIC_ENTERTEXT            5136
#define IDC_TEXT                        5137
#define IDC_QUICKCMDS                   5138
#define IDC_STATIC_KICKIT               5139
#define IDC_ENABLE_SERVER               5140
#define IDC_KICKIT_ROOM                 5141
#define IDC_ADD_KICKITADMIN             5142
#define IDC_STATIC_ADMINS_KICKIT        5143
#define IDC_ADD_KICKITPASSWORD          5144
#define IDC_ADMIN_ADD                   5145
#define IDC_ADMINLIST                   5146
#define IDC_ADMIN_REMOVE                5147
#define IDC_STATIC_BOT                  5148
#define IDC_STATIC_BIND                 5149
#define IDC_BINDADDR                    5150
#define IDC_KICKITLOG                   5151
#define IDC_STATIC_LOG                  5152
#define IDC_STATIC_WARNINGBOT           5153
#define IDC_STATIC_ROOMNAME             5154
#define IDC_BOTROOM                     5155
#define IDC_STATIC_INTERVAL             5156
#define IDC_ANNOUNCE                    5157
#define IDC_STATIC_EVERY                5158
#define IDC_INTERVAL                    5159
#define IDC_LIMIT                       5160
#define IDC_STATIC_TRIGGER              5162
#define IDC_STATIC_RESPONSE             5163
#define IDC_TRIGGER                     5164
#define IDC_RESPONSE                    5165
#define IDC_ADDTRIGGER                  5166
#define IDC_COMMANDS                    5167
#define IDC_REMOVECMD                   5168
#define IDC_LEECHKICK                   5169
#define IDC_ENABLEBOT                   5170
#define IDC_WELCOME                     5171
#define IDC_STATIC_WELCOME              5172
#define IDC_STATIC_LEAVEEMPTY           5173
#define IDC_STATIC_SETNICKNAME          5174
#define IDC_STATIC_TIMERESOLUTION       5175
#define IDC_RESOLUTION                  5176
#define IDC_STATIC_MS                   5177
#define IDC_EDITCMD                     5178
#define IDC_STATIC_KICKITNOTICE         5179
#define IDC_MORONMODE                   5180
#define IDC_STATIC_MESSAGECOLOR         5181
#define IDC_ENABLEMSGCOLOR              5182
#define IDC_LIMITTOOPS                  5183
#define IDC_HELPCOLORS                  5184
#define IDC_STATIC_SECURITY             5185
#define IDC_IDIOT                       5186
#define IDC_STATIC_BENDMX               5187
#define IDC_USERLIST                    5188
#define IDC_TOP                         5190
#define IDC_HIDE                        5191
#define IDC_TRANSPARENCY                5192
#define IDC_STATIC_TRANS                5193
#define IDC_STATIC_100                  5194
#define IDS_ERROR_WRITECHANNELS         57345
#define IDS_CFG_MENU                    57346
#define IDS_BENDMX_CONFIG               57347
#define IDS_CFG_WINMX                   57348
#define IDS_HISTORY_MENU                57349
#define IDS_RCMSMENU                    57350
#define IDS_CMDMENU                     57351
#define IDS_KICK                        57352
#define IDS_KICKBAN                     57353
#define IDS_BAN                         57354
#define IDS_UNBAN                       57355
#define IDS_SENDMSG                     57356
#define IDS_RCMSREDIRECT                57357
#define IDS_RCMSKICK                    57358
#define IDS_RCMSKICKBAN                 57359
#define IDS_RCMSBAN                     57360
#define IDS_RCMSUNBAN                   57361
#define IDS_RCMSPRINTSTAT               57362
#define IDS_RCMSPRINTIP                 57363
#define IDS_RCMSADDADMIN                57364
#define IDS_RCMSREMOVEADMIN             57365
#define IDS_CHAT                        57366
#define IDS_IGNORE                      57367
#define IDS_WHOIS                       57368
#define IDS_BROWSE                      57369
#define IDS_HOTLISTADD                  57370
#define IDS_RCMSCMD                     57371
#define IDS_SELECTALL                   57372
#define IDS_COPY                        57373
#define IDS_SENDTOBROWSER               57374
#define IDS_SEARCHGOOGLE                57375
#define IDS_QUOTE                       57376
#define IDS_COPYROOM                    57377
#define IDS_CLEARSCREEN                 57378
#define IDS_UNIGNORE                    57379
#define IDS_COPYUSERNAME                57380
#define IDS_ADVANCED                    57381
#define IDS_DISPLAYCHANNEL              57382
#define IDS_AWAYCONTROL                 57383
#define IDS_TEXTTRICKS                  57384
#define IDS_DOWNUP                      57385
#define IDS_LOCALTIME                   57386
#define IDS_LAG                         57387
#define IDS_WINAMP                      57388
#define IDS_OS                          57389
#define IDS_HACKER                      57390
#define IDS_BUBBLES                     57391
#define IDS_BOX                         57392
#define IDS_3DMSG                       57393
#define IDS_3DACTION                    57394
#define IDS_BACK                        57395
#define IDS_BACKSILENT                  57396
#define IDS_ZZZZZZZZ                    57397
#define IDS_WORK                        57398
#define IDS_SLEEP                       57399
#define IDS_AIR                         57400
#define IDS_BATHROOM                    57401
#define IDS_SMOKE                       57402
#define IDS_FOOD                        57403
#define IDS_BEER                        57404
#define IDS_TV                          57405
#define IDS_STORE                       57406
#define IDS_NONE                        57407
#define IDS_GOINGAWAY                   57408
#define IDS_SYSINFO                     57409
#define IDS_KICKIT_MISSING              57410
#define IDS_NOPRIMARY                   57411
#define IDS_NOROOM                      57412
#define IDS_WRONG                       57413
#define IDS_BOT_EMPTY                   57414
#define IDS_BOTWARNING                  57416
#define IDS_RCMSWARNING                 57417
#define IDS_SETBACK                     57418
#define IDS_SETSILENTBACK               57419
#define IDS_ZZZZZ                       57420
#define IDS_AWAYWORK                    57421
#define IDS_AWAYSLEEP                   57422
#define IDS_AWAYAIR                     57423
#define IDS_AWAYBATH                    57424
#define IDS_AWAYSMOKE                   57425
#define IDS_AWAYFOOD                    57426
#define IDS_AWAYBEER                    57427
#define IDS_AWAYTV                      57428
#define IDS_AWAYSTORE                   57429
#define IDS_AWAYNONE                    57430
#define IDS_AWAYCUSTOM                  57431
#define IDS_READMSG                     57432
#define IDS_HELPCOLORS                  57433
#define IDS_BUBBLESCOLOR                57434
#define IDS_SETTINGS                    57435
#define IDS_GENERAL                     57436
#define IDS_COLORS                      57437
#define IDS_MSG                         57438
#define IDS_FILTER                      57439
#define IDS_KICKIT                      57440
#define IDS_BOT                         57441
#define IDS_ABOUT                       57442
#define IDS_PLUGIN                      57443
#define IDS_DESC                        57444
#define IDS_AUTHOR                      57445
#define IDS_HOOKRESTORED                57446
#define IDS_ROOMCONNECTED               57447
#define IDS_LOCALTIMECH                 57448
#define IDS_ROOMREDIRECTED              57449
#define IDS_TOPICIS                     57451
#define IDS_WINAMPNOT                   57452
#define IDS_SYSUPTIME                   57453
#define IDS_BENDMX1STLINE               57454
#define IDS_SYSSTRING                   57455
#define IDS_CUSTOMIZE                   57456
#define IDS_EDITRCMSMENU                57457
#define IDS_CHATINFO                    57458
#define IDS_ROOMVERSION                 57459
#define IDS_COPYIP                      57460
#define IDS_NOIP                        57461
#define IDS_USERS                       57462
#define IDS_COLOREDTEXT                 57463
#define IDS_UPTIME                      57464
#define IDS_RCMSKICKBAN5                57465
#define IDS_RCMSDEVOICE                 57466
#define IDS_RCMSVOICE                   57467
#define IDS_CUSTOM                      57468
#define IDS_WELCOMEMSG                  57469
#define IDS_USERLISTHEADER              57470
#define IDS_SHOWADMINWND                57471

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5195
#define _APS_NEXT_SYMED_VALUE           57449
#endif
#endif
